const assert = require("node:assert/strict");
(async () => {
  const core = await import("../src/core/exporter.js");
  const posts = [{ id: "p-1", channel: "Pilot Channel", publishedAt: "3:00 PM, 8/19/2026", date: { iso: "2026-08-19", status: "parsed" }, text: 'Quote "test", with comma', media: [{ type: "image", url: "https://example.test/image", filename: "image.jpg" }] }, { id: "p-2", channel: "Pilot Channel", publishedAt: "8/20/2026", date: { iso: "2026-08-20", status: "parsed" }, text: "Second post", media: [] }];
  const jsonl = core.toJsonl(posts).trim().split("\n").map(JSON.parse);
  const csv = core.toCsv(posts);
  const result = core.validateExportSchemas(posts);
  assert.equal(result.ok, true, result.errors.join("; "));
  assert.equal(result.postCount, 2);
  assert.equal(result.mediaCount, 1);
  assert.equal(jsonl.length, 2);
  assert.equal(jsonl[0].schemaVersion, 2);
  assert.equal(jsonl[0].channel.name, "Pilot Channel");
  assert.match(csv, /post_id,|"post_id","channel"/);
  assert.match(csv, /"Quote ""test"", with comma"/);
  const invalid = core.validateExportSchemas([{ id: "bad", channel: "", media: "not-array" }]);
  assert.equal(invalid.ok, false);
  assert.ok(invalid.errors.some((error) => error.includes("channel.name")));
  console.log(JSON.stringify({ valid: result, invalidErrors: invalid.errors, status: "PASS" }, null, 2));
})().catch((error) => { console.error(error.stack || error.message); process.exit(1); });
